default:
  - build

test:
  - connect:serve
  - sauce_connect
  - shell:protractor
  - sauce-connect-close

local-test:
  - connect:serve
  - shell:protractor

build:
  - clean
  - jshint:lib
#  - jscs:lib
  - umd
  - concat
  - copy:client
  - local-test
  - uglify
